app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from errors.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('malling.urls', namespace='malling')),

]

handler404 = custom_404_view

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name='orders'

urlpatterns = [
    path('create-order/',views.create_order, name='create_order'),
    ]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

# Create your models here.



class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0



class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата картой")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    coment_order = models.TextField(null=True, blank=True, verbose_name="Коментрарий к заказу")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    
    
    
    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель   "
    

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус товара")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)


    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
from django import forms

from orders.models import Order

class CreateOrderForm(forms.ModelForm):
    class Meta:
        model=Order
        fields=['first_name','last_name','phone_number','delivery_address','payment_on_get','coment_order']
    
    
    
    first_name=forms.CharField()
    last_name=forms.CharField()
    phone_number=forms.CharField()
    delivery_address=forms.CharField()
    payment_on_get=forms.ChoiceField(choices=[("0", False),("1", True),],)
    coment_order= forms.CharField(required=False)
    

orders/views.py
import uuid
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.urls import reverse
from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from yookassa import Payment,Configuration
from django.conf import settings

Configuration.account_id = settings.YOOKASSA_SHOP_ID
Configuration.secret_key = settings.YOOKASSA_SECRET_KEY

def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # Создать заказ
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                            is_paid=form.cleaned_data['payment_on_get'],
                            coment_order=form.cleaned_data['coment_order'],
                        )

                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.products_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Недостаточное количество товара {name} на складе. В наличии - {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()


                        payment_on_get = form.cleaned_data['payment_on_get']
                        print(payment_on_get)
                        if payment_on_get == '1':
                            # Оплата через YooKassa
                            idempotence_key = uuid.uuid4()
                            total_price = cart_item.products_price()
                            currency = 'RUB'
                            description = 'Оплата товаров из корзины'

                            payment = Payment.create({
                                'amount': {
                                    'value': str(total_price),
                                    'currency': currency
                                },
                                'confirmation': {
                                    'type': 'redirect',
                                    'return_url': request.build_absolute_uri(reverse('user:profile'))
                                },
                                'capture': True,
                                'test': True,
                                'description': description
                            }, idempotence_key)

                            confirmation_url = payment.confirmation.confirmation_url
                            cart_items.delete()
                            return redirect(confirmation_url)
                        else:
                            cart_items.delete()
                            return redirect('user:profile')
            except ValidationError as e:
                return redirect('cart:order')

    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }
        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'Home - Оформление заказа',
        'form': form,
        'orders': True,
    }
    return render(request, 'orders/create_order.html', context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{%user_carts request as carts%}
{% block content %}
<div class="checkout-main-area pt-120 pb-120">
    <div class="container">
            <div class="checkout-wrap pt-30">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="billing-info-wrap mr-50">
                            <h3>Платежные данные</h3>
                            <form id="form" action="{% url "orders:create_order" %}" method='post'>
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="billing-info mb-20">
                                            <label for="id_first_name" class="required">Имя*</label>
                                            <input id="id_first_name" name="first_name" class="billing-address" placeholder="Имя" type="text" required>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="billing-info mb-20">
                                            <label for="id_last_name" class="required">Фамилия*</label>
                                            <input id="id_last_name" name="last_name" class="billing-address" placeholder="Фамилия" type="text"  required>
                                        </div>
                                    </div>
                                  
                                    <div class="col-lg-12 col-md-12">
                                        <div class="billing-info mb-20">
                                            <label for="id_phone_number" class="required">Телефон*</label>
                                            <input id="id_phone_number" name="phone_number" class="billing-address" placeholder="Телефон" type="text" required>
                                        </div>
                                    </div>
                                    <div class="col-lg-12 col-md-12">
                                        <div class="billing-info mb-20">
                                            <label for="id_delivery_address">Адрес*</label>
                                            <input id="id_delivery_address" name="delivery_address" class="billing-address" placeholder="Адрес" type="text">
                                        </div>
                                    </div>
                                </div>
                                <div class="additional-info-wrap">
                                    <label for="id_coment_order">Коментрарий к заказу</label>
                                    <textarea id="id_coment_order"  name="coment_order" placeholder="Коментрарий к вашему заказу, например, особые указания по доставке."></textarea>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="your-order-area">
                            <h3>Ваш заказ</h3>
                            <div class="your-order-wrap gray-bg-4">
                                <div class="your-order-info-wrap">
                                    <div class="your-order-info">
                                        <ul>
                                            <li>Товары<span>Сумма</span></li>
                                        </ul>
                                    </div>
                                    <div class="your-order-middle">
                                        <ul>
                                        {% for cart in carts  %}
                                            <li>{{cart.product.name}}   X {{cart.quantity}} <span>{{cart.products_price}} ₽</span></li>
                                        {% endfor %}
                                            
                                        </ul>
                                    </div>
                                    <div class="your-order-info order-total">
                                        <ul>
                                            <li>Итоговая сумма: <span>{{carts.total_price}} ₽ </span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="payment-method">
                                    <div class="pay-top sin-payment">
                                        <input id="id_payment_on_get" class="input-radio" type="radio" value="1" checked="checked" name="payment_on_get" form="form">
                                        <label for="id_payment_on_get">БАНКОВСКОЙ КАРТОЙ </label>
                                        <div class="payment-box payment_method_bacs">
                                            <p>Произведите платеж непосредственно на наш банковский счет. </p>
                                        </div>
                                    </div>
                                    <div class="pay-top sin-payment">
                                        <input id="id_payment_on_get" class="input-radio" type="radio" value="0" name="payment_on_get" form="form">
                                        <label for="id_payment_on_get">ОПЛАТА ПРИ ПОЛУЧЕНИИ</label>
                                        <div class="payment-box payment_method_bacs">
                                            <p>Оплачивайте при получении</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="Place-order">
                                <a name="yookassa-payment" id="sumbit" href="#">Оплатить</a>
                            </div>
                        </div>
                    </div>
              
                </div>
            </div>
        
    </div>
</div><script>
    document.getElementById("sumbit").addEventListener("click", function(event) {
      event.preventDefault(); // Предотвращаем действие по умолчанию (переход по ссылке)
      document.getElementById("form").submit(); // Отправляем форму
    });
    </script>
{% endblock content %}