app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from errors.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('malling.urls', namespace='malling')),

]

handler404 = custom_404_view

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import  path

from carts import views


app_name='carts'

urlpatterns = [
    path('cart_add/',views.cart_add, name='cart_add'),
    path('cart_remove/',views.cart_remove, name='cart_remove'),
    path('cart_remove/<int:cart_id>/',views.cart_removepage, name='cart_remove'),
    ]

goods/urls.py
from django.urls import  path

from goods import views


app_name='goods'

urlpatterns = [
    path('search/',views.catalog, name='search'),
    path('<slug:category_slug>/',views.catalog, name='index'),
    path('product/<slug:product_slug>/',views.product, name='product'),
    ]

goods/models.py
from django.db import models
from django.urls import reverse

# Create your models here.



class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"
    
    def __str__(self):
        return self.name



class Products(models.Model):
    shoes = 'shoes'
    Outerwear = 'Outerwear'
    t_shirts = 't_shirts'
    trousers='trousers'
    Costumes='Costumes'
    Sportswear='Sportswear'
    Accessories='Accessories'
    Dresses='Dresses'
    Overalls='Overall'
    sundresses='sundresses'
    no_sub_categories='---'

    LEVEL_CHOICES = (
        (no_sub_categories, '---'),
        (shoes, 'Обувь'),
        (Outerwear, 'Верхняя одежда'),
        (t_shirts, 'Футболки'),
        (trousers,'брюки'),
        (Costumes,'Костюмы'),
        (Sportswear,'Спортивная одежда'),
        (Accessories,'Аксессуары'),
        (Dresses,'Платья'),
        (Overalls,'Комбинезоны'),
        (sundresses,'сарафаны')
    )
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    mini_description = models.TextField(blank=True, null=True, verbose_name="Мини описание")
    image = models.ImageField(
        upload_to="goods_image", blank="True", null=True, verbose_name="Изображение"
    )
    price = models.DecimalField(
        default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена"
    )
    discount = models.DecimalField(
        default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена со скидкой"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(
        to=Categories, on_delete=models.CASCADE, verbose_name="Категория"
    )
    sub_category = models.CharField(max_length=150, choices=LEVEL_CHOICES, default=no_sub_categories,verbose_name="Подкатегория")
    articul=models.CharField(max_length=5,unique=True,verbose_name='Артикул')
    country=models.CharField(max_length=150,blank=True,verbose_name='Страна производства')
    size=models.CharField(max_length=2,blank=True,verbose_name='Размер')
    structure=models.CharField(max_length=400,blank=True,verbose_name='Состав')
    color=models.CharField(max_length=100,blank=True,verbose_name='Цвет')
    brand=models.CharField(max_length=100,blank=True,verbose_name='Бренд')


    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering=("id",)
    
    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from goods.models import Categories, Products
from goods.utils import q_search

# Create your views here.

def catalog(request,category_slug=None):
    
    page=request.GET.get('page', 1)
    onpage=request.GET.get('onpage',12)
    sorted=request.GET.get('sorted',)
    query=request.GET.get('search',)
    brands=request.GET.get('brands',)
    color=request.GET.get('color',)
    country=request.GET.get('country',)
    
    
    if category_slug=='all':
        goods=Products.objects.all()
        title='Все товары'
    elif query:
        goods=q_search(query)
        title=query
    else:
        goods=Products.objects.filter(category__slug=category_slug)
        title=Categories.objects.filter(slug=category_slug).first()

         

    if brands:
        goods=goods.filter(brand=brands)
    
    if color:
        goods=goods.filter(color=color)
    
    if country:
        goods=goods.filter(country=country)


    if sorted == 'price_desc':
        goods=goods.order_by('-price')
    elif sorted == 'price_asc':
        goods=goods.order_by('price')


    if onpage:
        paginator=Paginator(goods,int(onpage))
        current_page=paginator.page(int(page))
            
    else:
        paginator=Paginator(goods,1)
        current_page=paginator.page(int(page))
    
    current_url = request.path

    context={
        'title': title,
        'goods':current_page,
        'slug_url':category_slug,
        'onpage':onpage,
        'current_url':current_url,
        
}

    return render(request,'goods/catalog.html',context)



def product(request,product_slug):

    product=Products.objects.get(slug=product_slug)
    goods=Products.objects.all()[:4]

    context={
        'product':product,
        'title':product.name,
        'goods':goods,
    }

    return render(request,'goods/product.html',context=context)

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="product-details-area pt-120 pb-115">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-5">
                <div class="product-details-fixed-img">
                    <div class="easyzoom-style">
                        <div class="easyzoom easyzoom--overlay">
                            {% if product.image %}
                                <a href="{{product.image.url}}">
                                    <img src="{{product.image.url}}" alt="">
                                </a>
                            {% else %}
                            <a href="{% static "deps/images/product/product-14.jpg" %}">
                                <img src="{% static "deps/images/product/product-14.jpg" %}" alt="{{product.name}}">
                                {% endif %}
                            </a>
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="product-details-content pro-details-content-mrg">
                    <h2>{{product.name}}</h2>
                    <p class="mt-3">{{product.mini_description}}</p>
                    <div class="pro-details-price">
                        <span class="new-price">{{product.price}} ₽</span>
                    </div>
                    
                    <div class="pro-details-size">
                        <span>Размер:</span>
                        <div class="pro-details-size-content">
                            <ul>
                                <li><a >{{product.size}}</a></li>

                        </div>
                    </div>
                    <div class="product-details-meta">
                        <ul>
                            <li><span>Категория:</span> <a href="{% url "catalog:index" product.category_id %}">Мужская одежда</a></li>
                        </ul>
                    </div>
        
                    <div class="pro-details-action-wrap mt-3">
                        <div class="pro-details-add-to-cart">
                            <a class="add-to-cart" title="Add to Cart" href="{% url "cart:cart_add"%}" data-product-id={{product.id}}> {% csrf_token %} Добавить в корзину</a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="description-review-wrapper pb-110">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="dec-review-topbar nav mb-45">
                    <a class="active" data-toggle="tab" href="#des-details1">Описание</a>
                    <a data-toggle="tab" href="#des-details2">Характеристики</a>
                </div>
                <div class="tab-content dec-review-bottom">
                    <div id="des-details1" class="tab-pane active">
                        <div class="description-wrap">
                            <p>{{product.description}}</p> 
                        </div>
                    </div>
                    <div id="des-details2" class="tab-pane">
                        <div class="specification-wrap table-responsive">
                            <table>
                                <tbody>
                                    <tr>
                                        <td class="title width1">Артикул</td>
                                        <td>{{product.articul}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title width1">Состав</td>
                                        <td>{{product.structure}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title width1">Страна производства</td>
                                        <td>{{product.country}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title width1">Бренд</td>
                                        <td>{{product.brand}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title width1">Цвет</td>
                                        <td>{{product.color}}</td>
                                    </tr>
                                    <tr>
                                        <td class="title width1">Размер</td>
                                        <td>{{product.size}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="related-product pb-115">
    <div class="container">
        <div class="section-title mb-45 text-center">
            <h2>Рекомендуемые товары</h2>
        </div>
        <div class="related-product-active">
            {% for product in goods %}
            <div class="product-plr-1">
                <div class="single-product-wrap">
                    <div class="product-img product-img-zoom mb-15">
                        <a href="{% url "catalog:product" product.slug %}">
                            {% if product.image %}
                            <img src="{{product.image.url}}" alt="">
                            {% else %}
                                <img src="{% static "deps/images/product/product-14.jpg" %}" alt="{{product.name}}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="product-content-wrap-2 text-center">
                        <h3><a href="{% url "catalog:product" product.slug %}">{{product.name}}</a></h3>
                        <div class="product-price-2">
                            <span>{{product.price}} ₽</span>
                        </div>
                    </div>
                    <div class="product-content-wrap-2 product-content-position text-center">
                        <h3><a href="{% url "catalog:product" product.slug %}">{{product.name}}</a></h3>
                        <div class="product-price-2">
                            <span>{{product.price}} ₽</span>
                        </div>
                        <div class="pro-add-to-cart">
                            <a href="{% url "cart:cart_add"%}" class="btn btn-dark add-to-cart " data-product-id={{product.id}} > {% csrf_token %}Добавить в корзину</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
           
        </div>
    </div>
</div>


{% endblock content %}