app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from errors.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('malling.urls', namespace='malling')),

]

handler404 = custom_404_view

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import  path

from carts import views


app_name='carts'

urlpatterns = [
    path('cart_add/',views.cart_add, name='cart_add'),
    path('cart_remove/',views.cart_remove, name='cart_remove'),
    path('cart_remove/<int:cart_id>/',views.cart_removepage, name='cart_remove'),
    ]

goods/urls.py
from django.urls import  path

from goods import views


app_name='goods'

urlpatterns = [
    path('search/',views.catalog, name='search'),
    path('<slug:category_slug>/',views.catalog, name='index'),
    path('product/<slug:product_slug>/',views.product, name='product'),
    ]

orders/urls.py
from django.urls import path

from orders import views

app_name='orders'

urlpatterns = [
    path('create-order/',views.create_order, name='create_order'),
    ]

users/urls.py
from django.urls import  path

from users import views


app_name='users'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('registration/',views.registration, name='registration'),
    path('profile/',views.profile, name='profile'),
    path('user-cart/',views.users_cart, name='user_cart'),
    path('logout/',views.logout, name='logout'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

# Create your models here.



class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0



class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата картой")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    coment_order = models.TextField(null=True, blank=True, verbose_name="Коментрарий к заказу")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    
    
    
    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель   "
    

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус товара")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)


    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    phone=models.CharField(max_length=11,blank=True,verbose_name='Телефон')
    address=models.TextField(max_length=200,blank=True,verbose_name='Адрес')


    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"
    
    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    class Meta:
        model=User
        fields=['username','password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
        
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "address",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    address = forms.CharField()
    email = forms.CharField()
        

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from carts.models import Cart
from orders.models import Order, OrderItem
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from users.models import User

# Create your views here.


def login(request):
    
    if request.method=='POST':
        form=UserLoginForm(data=request.POST)
        if form.is_valid():
            username=request.POST['username']
            password=request.POST['password']
            user=auth.authenticate(username=username,password=password)
            
            session_key=request.session.session_key

            if user:
                auth.login(request,user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                    

                if request.POST.get('next',None):
                    
                    return HttpResponseRedirect(request.POST.get('next'))
                    
                return HttpResponseRedirect(reverse('user:profile'))
    else:
        form=UserLoginForm()

    context={
        'title':'Авторизация',
        'form':form
    }
    return render(request,'users/login.html',context)


def registration(request):
    if request.method=='POST':
        form=UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            session_key=request.session.session_key
            user=form.instance
            
            auth.login(request,user)
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
            

            return HttpResponseRedirect(reverse('main:index'))
    else:
        form=UserRegistrationForm()
    

    context={
        'title':'Регистрация',
        'form':form
    }
    return render(request,'users/registration.html',context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успешно обновлен")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = ProfileForm(instance=request.user)

    orders = Order.objects.filter(user=request.user).prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            ).order_by("-id")

    


    context={
        'title':'Кабинет',
        'form':form,
        'orders':orders
    }
    return render(request,'users/profile.html',context)



def users_cart(request,):
    context={
        'title':'Корзина'
    }
    
    return render(request,'users/users_cart.html' ,context)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="my-account-wrapper pt-120 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                
                <!-- My Account Page Start -->
                <div class="myaccount-page-wrapper">
                    <!-- My Account Tab Menu Start -->
                    <div class="row">
                        <div class="col-lg-3 col-md-4">
                            <div class="myaccount-tab-menu nav" role="tablist">
                                <a href="#dashboad" class="active" data-toggle="tab"><i class="fa fa-dashboard"></i>
                                    Панель управления</a>
                                <a href="#address-edit" data-toggle="tab"><i class="fa fa-map-marker"></i>Профиль</a>
                                <a href="#orders" data-toggle="tab"><i class="fa fa-cart-arrow-down"></i>Заказы</a>
                                <a href="#account-info" data-toggle="tab"><i class="fa fa-user"></i> Настройки профиля</a>
                                <a href="{% url "user:logout" %}"><i class="fa fa-sign-out"></i>Выход</a>
                            </div>
                        </div>
                        <!-- My Account Tab Menu End -->
                        <!-- My Account Tab Content Start -->
                        <div class="col-lg-9 col-md-8">
                            <div class="tab-content" id="myaccountContent">
                                <!-- Single Tab Content Start -->
                                <div class="tab-pane fade show active" id="dashboad" role="tabpanel">
                                    <div class="myaccount-content">
                                        <h3>Панель управления</h3>
                                        <div class="welcome">
                                            <p>Здравствуйте, <strong>{{form.first_name.value}}</strong></p>
                                        </div>

                                        <p class="mb-0">С помощью панели управления вашей учетной записи. Вы можете легко проверять и просматривать свои последние заказы, управлять адресами доставки, а также редактировать свой пароль и данные учетной записи.</p>
                                    </div>
                                </div>
                                <!-- Single Tab Content End -->
                                <!-- Single Tab Content Start -->
                                <div class="tab-pane fade" id="orders" role="tabpanel">
                                    <div class="myaccount-content">
                                        <h3>Заказы</h3>
                                        {% if orders %}
                                        <div class="myaccount-table table-responsive text-center">
                                            <table class="table table-bordered">
                                                <thead class="thead-light">
                                                    <tr>
                                                        <th>Название</th>
                                                        <th>Дата</th>
                                                        <th>Статус</th>
                                                        <th>Сумма</th>
                                                        
                                                    </tr>
                                                </thead>
                                                <tbody>
                                            {% for order in orders %}     
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td>{{item.name}}</td>
                                                    <td>{{item.created_timestamp|date:"d.m.Y"}}</td>
                                                    <td>{{item.status}}</td>
                                                    <td>{{ item.price}}</td>
                            
                                                {% endfor %}
                                            {% endfor %}
                                                </tr>
                                                    
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                        {% else %}
                                            <p>Заказов нет, но идеи и страсть к красоте все еще здесь. Пока мы ожидаем ваших предпочтений, давайте вдохновимся вместе, чтобы сделать вашу покупку незабываемой.</p>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="address-edit" role="tabpanel">
                                    <div class="myaccount-content">
                                        <h3>Мой профиль</h3>
                                        <address>
                                            <p><strong>{{form.first_name.value}} {{form.last_name.value}}</strong></p>
                                            <p>Адрес: {{form.address.value}}</p>
                                            <p>E-mail: {{form.email.value}}</p>
                                        </address>
                                        <p> Для изменения информации перейдите в настройки профиля</p>
                                    </div>
                                </div>
                                <!-- Single Tab Content End -->
                                <!-- Single Tab Content Start -->
                                <div class="tab-pane fade" id="account-info" role="tabpanel">
                                    <div class="myaccount-content">
                                        <h3>Настройки профиля</h3>
                                        <div class="account-details-form">
                                            <form action="{% url "user:profile" %}" method="POST">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="single-input-item">
                                                            <label for="id_first_name" class="required">Имя</label>
                                                            <input type="text" id="id_first_name"
                                                             name="first_name"
                                                             value="{{form.first_name.value}}" required/>
                                                             {% if form.first_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="single-input-item">
                                                            <label for="id_last_name" class="required">Фамилия</label>
                                                            <input type="text" id="id_last_name"
                                                            name="last_name"
                                                            value="{{ form.last_name.value }}"/>
                                                            {% if form.last_name.errors %}
                                                            <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="single-input-item">
                                                    <label for="id_address" class="required">Адрес</label>
                                                    <input type="text" id="id_address" name="address"
                                                    placeholder="Адрес"
                                                    value="{{ form.address.value }}" required />
                                                    {% if form.address.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                    {% endif %}
                                                </div>
                                                <div class="single-input-item">
                                                    <label for="id_email" class="required">Email</label>
                                                    <input type="email" id="id_email"
                                                    name="email"
                                                    placeholder="Введите ваш email *youremail@example.com"
                                                    value="{{ form.email.value }}" required />
                                                    {% if form.email.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                    {% endif %}
                                                </div>
                                                <div class="single-input-item">
                                                    <button class="check-btn sqr-btn ">Сохранить изменения</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div> <!-- Single Tab Content End -->
                            </div>
                        </div> <!-- My Account Tab Content End -->
                    </div>
                </div> <!-- My Account Page End -->
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="login-register-area pt-115 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                <div class="login-register-wrapper">
                    <div class="login-register-tab-list nav">
                        <a href="{% url "users:login" %}">
                            <h4>Вход</h4>
                        </a>
                        <a class="active">
                            <h4> Регистрация </h4>
                        </a>
                    </div>
                    <div class="tab-content">
                        <div class="login-form-container">
                            <div class="login-register-form">
                                <form action="{% url "user:registration" %}" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="id_first_name" class="form-label">Имя*</label>
                                            <input type="text" class="form-control" id="id_first_name"
                                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                                name="first_name"
                                                placeholder="Введите ваше имя" required>
                                                {% if form.first_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_last_name" class="form-label">Фамилия*</label>
                                            <input type="text" class="form-control" id="id_last_name"
                                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                                name="last_name"
                                                placeholder="Введите вашу фамилию" required>
                                                {% if form.last_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                                {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_username" class="form-label">Имя пользователя*</label>
                                            <input type="text" class="form-control" id="id_username"
                                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                                name="username"
                                                placeholder="Введите ваше имя пользователя" required>
                                                {% if form.username.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                                {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_email" class="form-label">Email*</label>
                                            <input type="email" class="form-control" id="id_email"
                                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                                name="email"
                                                placeholder="Введите ваш email" required>
                                                {% if form.email.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_password1" class="form-label">Пароль*</label>
                                            <input type="password" class="form-control" id="id_password1"
                                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                                name="password1"
                                                placeholder="Введите пароль" required>
                                                {% if form.password1.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                                {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                            <input type="password" class="form-control" id="id_password2"
                                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                                name="password2"
                                                placeholder="Подтвердите пароль" required>
                                                {% if form.password2.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                                {% endif %}
                                        </div>
                                    </div>
                                    <div class="button-box">
                                        <button type="submit">Регистрация</button>
                                    </div>
                                </form>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}


{% block content %}
{% load carts_tags %}

{%user_carts request as carts%}
<div class="cart-main-area pt-115 pb-120">
            <div class="container" >
                <div class="cart-header">
                    <h3 class="cart-page-title">Корзина</h3>
                    <h3 class="cart-page-title">Итоговая сумма:{{carts.total_price}}₽</h3>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <form action="#">
                            <div class="table-content table-responsive cart-table-content">
                            {% if carts %}
                                <table>
                                    <tbody>
                                    {% for cart  in carts  %}
                                        <tr > 
                                            <td class="product-thumbnail">
                                                <a href="{% url "catalog:product" cart.product.slug %}">
                                                    {% if cart.product.image %}
                                                        <img class="img-fluid ml-10" src="{{cart.product.image.url}}" alt="">
                                                    {% else %}
                                                        <img src="{% static "deps/images/product/product-14.jpg" %}" alt="{{product.name}}">
                                                    {% endif %}
                                                </a>
                                            </td>
                                            <td class="product-name font-weight-bold"><a href="{% url "catalog:product" cart.product.slug %}">{{cart.product.name}}</a></td>
                                            <td class="product-name ">{{cart.product.price}} ₽</td>
                                            <td class="product-name">{{cart.quantity}} шт</td>
                                            <td class="product-subtotal">{{cart.products_price}}₽</td>
                                            <td class="product-remove">
                                             <a href="{% url "cart:cart_remove" cart.id %}" data-cart-id="{{cart.id}}">{% csrf_token %}<i class="icon_close"></i></a>
                                            </td>
                                    
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            {% else %}
                                <p>Ваша корзина ждет своего момента славы! Давайте воплотим в жизнь ваши желания, наполняя ее эксклюзивными предметами из нашего ассортимента.</p>
                            {% endif %}
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="cart-shiping-update-wrapper">
                                        <div class="cart-shiping-update">
                                            <a href="{% url "user:user_cart" %}">Обновить</a>
                                        </div>
                                        <div class="cart-clear">
                                            
                                            <a href="{% url "orders:create_order" %}">Оплатить</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}