app/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from errors.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('malling.urls', namespace='malling')),

]

handler404 = custom_404_view

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import  path

from main import views


app_name='main'

urlpatterns = [
    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),

]

main/models.py
from django.db import models


class Contact(models.Model):
    username=models.CharField(max_length=50,blank=True, null=True, verbose_name="Логин")
    e_mail=models.CharField(max_length=50,blank=True, null=True,verbose_name="E-mail")
    subject=models.CharField(max_length=100,blank=True, null=True, verbose_name="Тема")
    coment_text = models.TextField(null=True, blank=True, verbose_name="Сообщение")

    
    class Meta:
        db_table = "contact"
        verbose_name = "Обратная связь"
        verbose_name_plural = "Обратная связь"

    def __str__(self):
        return f"Оюращение № {self.pk} | Пользователь {self.username}"

main/forms.py
from django import forms

from main.models import Contact



class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields=['username','e_mail','subject','coment_text']

    username=forms.CharField()
    e_mail=forms.CharField()
    subject=forms.CharField()
    coment_text=forms.CharField()



# class MailingForm(forms.ModelForm):
#     class Meta:
#         model=Mailing
#         fields=['e_mail']

#     e_mail=forms.CharField()

main/views.py
from django.shortcuts import  render,redirect
from goods.models import Categories, Products


from django.http import HttpResponseRedirect
from django.urls import reverse

from main.forms import ContactForm



def index(request):

    goods=Products.objects.all()[:3]
    context= {
        'title':'Главная',
        'goods':goods,
    }

    return render(request, 'main/index.html',context)


def about(request):

    context={
        'title':'О нас',
        
    }
    return render(request,'main/about.html',context)


def contact(request):
    if request.method=='POST':
        form=ContactForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:index'))
    
    else:
        form=ContactForm()

    context={
        'title':'Контакты',
        'form':form
    }
    return render(request,'main/contact.html',context)

main/templates/main/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="about-us-area pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-3">
                        <div class="about-us-logo">
                            <img src="{% static "deps/images/about/logo.png" %}" alt="logo">
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9">
                        <div class="about-us-content">
                            <h3>О компании</h3>
                            <p>Концепция бизнеса Norda store заключается в том, чтобы предлагать моду и качество по лучшей цене. С момента своего основания в 2018 году он превратился в один из лучших модных магазинов России.</p>
                            <div class="signature">
                                <h2>David Moye</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="service-area pb-120">
            <div class="container">
                <div class="service-wrap-border service-wrap-padding-3">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6 col-12 service-border-1">
                            <div class="single-service-wrap-2 mb-30">
                                <div class="service-icon-2 icon-red">
                                    <i class="icon-cursor"></i>
                                </div>
                                <div class="service-content-2">
                                    <h3>Бесплатная доставка</h3>
                                    <p>На сумму свыше 9999 ₽</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-12 service-border-1 service-border-1-none-md">
                            <div class="single-service-wrap-2 mb-30">
                                <div class="service-icon-2 icon-red">
                                    <i class="icon-refresh "></i>
                                </div>
                                <div class="service-content-2">
                                    <h3>Возврат через 90 дней</h3>
                                    <p>Для решения любых проблем</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-12 service-border-1">
                            <div class="single-service-wrap-2 mb-30">
                                <div class="service-icon-2 icon-red">
                                    <i class="icon-credit-card "></i>
                                </div>
                                <div class="service-content-2">
                                    <h3>Безопасный платеж</h3>
                                    <p>100% Гарантия</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                            <div class="single-service-wrap-2 mb-30">
                                <div class="service-icon-2 icon-red">
                                    <i class="icon-earphones "></i>
                                </div>
                                <div class="service-content-2">
                                    <h3>Поддержка 24 часа</h3>
                                    <p>Круглосуточная поддежка</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="team-area pb-90">
            <div class="container">
                <div class="section-title mb-45 text-center">
                    <h2>Наша команда</h2>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <img src="{% static "deps/images/team/team-1.jpg" %}" alt="">
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="social_facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="social_twitter"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="social_instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Михаил Зубенко</h4>
                                <span>Директор</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <img src="{% static "deps/images/team/team-2.jpg" %}" alt="">
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="social_facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="social_twitter"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="social_instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Мария Лесных</h4>
                                <span>Дизайнер</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <img src="{% static "deps/images/team/team-3.jpg" %}" alt="">
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="social_facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="social_twitter"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="social_instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Дмитрий Смирнов</h4>
                                <span>SEO-специалист </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="team-wrapper mb-30">
                            <div class="team-img">
                                <img src="{% static "deps/images/team/team-4.jpg" %}" alt="">
                                <div class="team-action">
                                    <a class="facebook" href="#">
                                        <i class="social_facebook"></i>
                                    </a>
                                    <a class="twitter" href="#">
                                        <i class="social_twitter"></i>
                                    </a>
                                    <a class="instagram" href="#">
                                        <i class="social_instagram"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="team-content text-center">
                                <h4>Петр Иванов</h4>
                                <span>Отдел продаж</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}
        

main/templates/main/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="contact-area pt-115 pb-120">
    <div class="container">
        <div class="contact-info-wrap-3 pb-85">
            <h3>Контактная информация</h3>
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <div class="single-contact-info-3 text-center mb-30">
                        <i class="icon-location-pin "></i>
                        <h4>Наш адрес</h4>
                        <p>Россия,Москва,улица Красная 123Б</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="single-contact-info-3 extra-contact-info text-center mb-30">
                        <ul>
                            <li><i class="icon-screen-smartphone"></i>+7 (900) 544-22-11</li>
                            <li><i class="icon-envelope "></i> <a href="#">info@example.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="single-contact-info-3 text-center mb-30">
                        <i class="icon-clock "></i>
                        <h4>Рабочие время</h4>
                        <p>Понедельник - Пятница. 10:00 - 18:00</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="get-in-touch-wrap">
            <h3>Связаться с нами</h3>
            <div class="contact-from contact-shadow">
                <form  action="{% url "main:contact" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <label for="id_username" class="required">Email*</label>
                            <input id="id_username" name="username" type="text" placeholder="Логин"required>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <label for="id_e_mail" class="required">Email*</label>
                            <input id="id_e_mail" name="e_mail" type="text" placeholder="Email"required>
                        </div>
                        <div class="col-lg-12 col-md-12">
                            <label for="id_subject" class="required">Email*</label>
                            <input id="id_subject" name="subject" type="text" placeholder="Тема" required>
                        </div>
                        <div class="col-lg-12 col-md-12">
                            <label for="id_coment_text" class="required">Email*</label>
                            <textarea id="id_coment_text" name="coment_text" placeholder="Ваше сообщение"></textarea>
                        </div>
                        <div class="col-lg-12 col-md-12">
                            <button class="submit" type="submit">Отправить сообщение</button>
                        </div>
                    </div>
                </form>
                <p class="form-messege"></p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}